### ISSUE TITLE
Feature request: caching

### ISSUE THREAD

**Issue by djibux** [Sichroteph/Weather-Graph#1]
Hello,

I would love it if your app could cache the last request.  By that I mean the app should open with the previous results and fetch newer data in the background.  That would enable being able to view the last weather request even when the phone cannot be reached or has no connection.

**Comment by Sichroteph** [comment]
Thanks for your request. However won't it be confusing for the average user that checks the weather once or twice a day ? Putting in cache ever variable is quite a long work and I am not sure what would be the benefits in an app. I often cache my watchfaces because the user will leave it only a few minutes for doing a specific task. But for weather graph I am afraid that it will blur the message here. But of course maybe i am wrong and if anyone is up to the task I will be glad to see the result :)

**Comment by djibux** [comment]
The thing is I often find myself away from my phone, outside, and sometimes want to double check when it will start to rain or rain heavily.  Caching is probably overkill, pinning a weather forecast to the timeline could be another solution.
